### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by dreierhi** [erikbrinkman/color-nonogram#1]
Hello,

today I tried to use this potentially wonderful tool for the first time. Instead of giving a solution the program just gave this:

```
/usr/local/lib/node_modules/color-nonogram/nonogram.js:39
    console.log(count(line).map(([e, c]) => {
                                 ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Thanks for investigating!

**Comment by erikbrinkman** [comment]
I haven't touched this code in a while, but the line you reference is an array destructing (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) which was added in ES6. What JavaScript engine are you using? E.g. node.js and version it browser and version?

**Comment by dreierhi** [comment]
Oh, how stupid. I assumed the node.js package in the Ubuntu repo was at least somehow up to date. Nope. Version 4.2.6 opposite to 8.11 being the latest LTS. Thank you anyway, even despite it was not your fault. I should really watch out for outdated packages.

**Comment by erikbrinkman** [comment]
Yeah, you should install node from their website. As you found out, the ubuntu package is horribly out of date. I'll also recommend the npm package `n`. It's a version manager for node, so after installing (e.g. with `npm i -g n`) you can use `n stable` to update node to its most recent stable node version.

**Comment by dreierhi** [comment]
Thank you for this useful suggestion, I immediately installed it.

Additionally I ran into another problem. I have no clue about JS and its possibilities. What does the function `verifyCounts` and is it supposed to use the undefined variable rKeys (and possibly cKeys)?

**Comment by erikbrinkman** [comment]
Thanks for pointing that out. My tests we're poorly written, so I didn't catch the syntax error instead of the intended error. That function checks to make sure that the counts are compatible, e.g. if there are two blues in the rows, there are two blues in the columns.

I just pushed a fix that now uses a linter and verifies the correct exceptions are thrown.

**Comment by dreierhi** [comment]
Thank you so much for fixing everything. With the correct error output I could finally understand the problem in my pattern. I have to say that I am impressed by your response time. Hopefully that's it from my side. Thanks again!
